spring:
  application:
    name: payment-service
  config:
    import: "optional:configserver:http://localhost:8088/"
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.vkvs8nl.mongodb.net/?retryWrites=true&w=majority
      database: ${MONGO_DATABASE}