# Configuration for the server, specifying the port on which the API Gateway will run.
server:
  port: 8061

# Configuration for connecting to Eureka for service registration and discovery.
eureka:
  client:
    serviceUrl:
      # Default Eureka server URL where service instances are registered and discovered.
      defaultZone: http://localhost:8761/eureka/

# Configuration for the Spring application, setting the name to "api-gateway."
spring:
  application:
    name: api-gateway

  # Configuration for Spring Cloud Gateway.
  cloud:
    gateway:
      routes:
        # Configuration for a route named "order-service."
        - id: order-service
          # URI indicating load balancing for the "order-service."
          uri: lb://order-service
          # Predicates define conditions for the route to be matched. In this case, matching requests with "/order/**" path.
          predicates:
            - Path=/order/**

        # Configuration for a route named "payment-service."
        - id: payment-service
          # URI indicating load balancing for the "payment-service."
          uri: lb://payment-service
          # Predicates define conditions for the route to be matched. In this case, matching requests with "/payment/**" path.
          predicates:
            - Path=/payment/**

# Configuration for management features, specifically tracing.
management:
  tracing:
    sampling:
      # Probability of sampling traces, set to 1.0 (100%) to capture all traces.
      probability: 1.0
